tier4/AutomanTools

.circleci/config.yml
Introduce CircleCI for quality assurance.
Since I only build docker image, need to add tests in the future.
=> Introduce CircleCI

automan/api/projects/jobs/serializer.py, automan/api/projects/originals/original_manager.py, automan/api/projects/originals/views.py
Add rosbag msg_type validation.
=> add label_type validation

automan/templates/top_base.html
Remove unused GOOGLE ANALITICS codes.
=> Remove GOOGLE ANALITICS

front/app/labeling_tool/annotation.js, front/app/labeling_tool/controls.jsx, front/app/labeling_tool/history.jsx, front/app/labeling_tool/image_label_tool.jsx, front/app/labeling_tool/pcd_label_tool.jsx
This PR is Labeling Tool's features https://github.com/tier4/AutomanTools/issues/8.
This design change includes:
- Redo / Undo
- Shortcuts: Ctrl+Z / Ctrl+Shift+Z
=> Labeling Tool Features: Redo / Undo

front/app/dashboard/components/annotation/entry.jsx, front/app/dashboard/components/dataset/annotationForm.jsx, front/app/dashboard/components/dataset/entry.jsx, front/app/dashboard/components/dataset/table.jsx, front/app/dashboard/components/original/table.jsx
- Move `create annotation` form
This PR is related to #19
- Annotations can be created from `Datasets` page
=> Move create annotation form

automan/api/projects/project_manager.py, automan/api/projects/serializer.py, automan/api/projects/views.py, front/app/dashboard/components/mypage/project_form.jsx, front/app/dashboard/components/project/entry.jsx, front/app/dashboard/components/project/klassset_klass_table.jsx
- Create `Klassets` and `Storages` at `Project` creation
- Move `Klasssets` form
- Automatically create LOCAL_NFS `storages`
- Add klassset validation
- Change some icons
- Added confirmation screen before submit
New `project form` is managed by step
=> Simplify project registration form

front/app/labeling_tool/annotation.js, front/app/labeling_tool/clipboard.jsx, front/app/labeling_tool/controls.jsx, front/app/labeling_tool/history.jsx
This PR is Labeling Tool's features https://github.com/tier4/AutomanTools/issues/8.
This design change includes:
- Copy / Paste
- Shortcuts: Ctrl+C / Ctrl+V
Labels can copy and paste on another frame.
Copy all labels.
=> Labeling Tool Features: Copy / Paste

front/app/dashboard/components/calibration/entry.jsx, front/app/dashboard/components/calibration/form.jsx, front/app/dashboard/components/calibration/table.jsx, front/app/dashboard/components/original/form.jsx
- Fix : `Cancel` button not working
- Fix:  Remove unused button
- Feature: Automatically choose `storage`
- Feature: calibration contents can be confirmed from web UI.
=> Improvement Raw & Calibration form

front/app/labeling_tool/annotation.js, front/app/labeling_tool/history.jsx, front/app/labeling_tool/pcd_label_tool.jsx
This PR is Labeling Tool's features https://github.com/tier4/AutomanTools/issues/8.
This design change includes:
- Z resizes
- Auto Set Height
=> Labeling Tool Features: Z axis controls

automan/api/projects/annotations/annotation_manager.py, front/app/dashboard/components/project/klassset_klass_table.jsx, front/app/labeling_tool/annotation.js
- Auto request to assign the instance id
- Support instance_id for Copy/Paste
This PR is front side update
https://github.com/tier4/AutomanTools/pull/31
=> Add Object Tracking GUI

front/app/labeling_tool/annotation.js, front/app/labeling_tool/base_label_tool.jsx, front/app/labeling_tool/controls.jsx
- Request to get lock when fetching label
- Release lock when exit with logout button
- use unlock API
This PR is related to Roadmap
https://github.com/tier4/AutomanTools/wiki
and backend PR
https://github.com/tier4/AutomanTools/pull/33
=> Add frame lock frontend

front/app/labeling_tool/pcd_label_tool.jsx
=> Revert "Fix set_height in labeling tool"

automan/api/projects/jobs/serializer.py, front/app/dashboard/components/original/candidateSelect2D.jsx, front/app/dashboard/components/original/candidateSelect2D3D.jsx, front/app/dashboard/components/original/extractorForm.jsx
- add candidate validation in extractor screen
- (previously, the `NEXT` button was always active)
- `NEXT` button is disabled when each column is not checked
=> Add validation to extractor screen

.dockerignore, Dockerfile
- Efficient use of docker layer cache
- apt-get, yarn, and COPY
- Reduce files to COPY
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
=> improve Dockerfile

front/app/labeling_tool/base_label_tool.jsx, front/app/labeling_tool/base_tool/loading_progress.jsx, front/app/labeling_tool/controls.jsx, front/app/labeling_tool/image_label_tool.jsx
- Fix the position of 2D preview area
- Reduce loading time during work
- Add frame data prefetching on initializing state
Preview area
=> Fix preview problems

setup/vagrant/automan-labeling.yaml
=> fix: add dependency

front/app/labeling_tool/annotation.js, front/app/labeling_tool/base_label_tool.jsx, front/app/labeling_tool/controls.jsx, front/app/labeling_tool/image_label_tool.jsx, front/app/labeling_tool/pcd_label_tool.jsx, front/app/labeling_tool/tool-style.js
Labeling Tool style changes.
- Show 2D labels on 3D tool
- Enable to use multi image dataset on frontend
Some bug fixes
- Hunging caused by unlimited parallel fetch when the prefetch phase.
- Excessive loading error indication
- Incomplete history undo
#8 multiple camera angles
=> Show 2D labels on editing 3D labels

automan/api/projects/originals/models.py
Bug Fix
Fix the bug that uploading files larger than 2GB fails.
https://github.com/tier4/AutomanTools/issues/71
=> Bug fix for uploading large files

front/app/labeling_tool/actions/annotation_action.js, front/app/labeling_tool/image_label_tool.jsx, front/app/labeling_tool/image_tool/image_bbox.js, front/app/labeling_tool/pcd_label_tool.jsx, front/app/labeling_tool/pcd_tool/box_frame_object.js, front/app/labeling_tool/pcd_tool/edit_bar.jsx, front/app/labeling_tool/pcd_tool/pcd_bbox.js, front/app/labeling_tool/reducers/annotation_reducer.js, front/app/labeling_tool/tool-style.js, front/app/services/request-client.js
Add 3D edit helper panels.
* Add 3D projection view from +Z/+X/+Y
* Add 3D bbox control slideres
And some bug fixes.
* Catch ignored mouse-up event
* Scale related bug
#8
=> Labeling tool 3d projection views

automan/api/projects/annotations/helpers/label_types/bb2d3d.py, front/app/labeling_tool/pcd_label_tool.jsx, front/app/labeling_tool/pcd_tool/pcd_bbox.js
**This is destructive change**
Change saving data format as follows.
* 3D size y: height_3d => length_3d
* 3D size z: length_3d => height_3d
* 3D yaw: rotation_y => yaw
And add 3D axis line.
=> CHANGE 3D AXIS AND YAW NAME

front/app/labeling_tool/pcd_tool/pcd_bbox.js
SWAP NAMES, WIDTH & LENGTH
#77
=> FIX 3D AXIS NAME

automan/api/projects/annotations/annotation_manager.py, automan/api/projects/annotations/helpers/memo.py, front/app/labeling_tool/annotation.js, front/app/labeling_tool/common_edit_bar.jsx, front/app/labeling_tool/controls.jsx, front/app/labeling_tool/image_label_tool.jsx, front/app/labeling_tool/pcd_tool/edit_bar.jsx, front/app/labeling_tool/reducers/annotation_reducer.js, front/app/labeling_tool/tool-style.js
Add memo area.
* You can write memo on each labels.
* When you copy the label, its memo is also copied.
=> Add label memo

automan/api/projects/jobs/serializer.py, automan/api/projects/jobs/views.py, front/app/dashboard/components/annotation/archive_dialog.jsx, front/app/dashboard/components/annotation/table.jsx
Add write image flag while archiving process.
=> Add write image flag

front/app/dashboard/components/annotation/table.jsx
Close dialog when it is archived.
=> Archive dialog bug fix

automan/api/projects/jobs/serializer.py, automan/libs/k8s/jobs/__init__.py, automan/libs/k8s/jobs/annotation_archiver.py, automan/libs/k8s/jobs/rosbag_analyzer.py, automan/libs/k8s/jobs/rosbag_extractor.py
- Shorten the TTL because the job remains after it is completed
=> feat: shorten job ttl

front/app/labeling_tool/pcd_tool/edit_bar.jsx
- Enable to change the value from the input
=> Change the value from the input

automan/api/projects/jobs/serializer.py, automan/api/projects/jobs/views.py, front/app/dashboard/components/original/candidateSelect2D.jsx, front/app/dashboard/components/original/candidateSelect2D3D.jsx
* Show dataset name input UI when raw extract start
* Add dataset name on config to extractor
Give the datasets identification name #96
=> Give the datasets identification name

front/app/dashboard/components/calibration/form.jsx, front/app/dashboard/components/original/form.jsx
Disable upload button during the upload.
=> Disable upload button during the upload

front/app/labeling_tool/pcd_tool/edit_bar.jsx
Fix the bug that ignored changes by sidebar at history.
=> Fix history bugs

front/app/dashboard/components/original/form.jsx
Enable to select and upload multiple bag files.
=> Fix multiple files bug

.github/dependabot.yml
=> Add target-branch dependabot
